<?php

namespace Tarea\ListadoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaRepository extends EntityRepository
{
     public function getTareas()
    {
        $qb = $this->createQueryBuilder('t')
                   ->select('t')
                   ->addOrderBy('t.fechaRealizar', 'ASC')
                   ->addOrderBy('t.prioridad', 'DESC');

        return $qb->getQuery()
                  ->getResult();
    }
}
